### PR TITLE
pass args to pnpm/action-setup instead of handling them here

### PR DESCRIPTION
**Pull request by poulet42**
This MR pass directly pnpm install's args to the original pnpm action as it already handled from there with the `run_install` input.

(please ignore changes on ci.yml, it's just to test regressions)

### CODE REVIEW

**Review by NullVoxPopuli — CHANGES_REQUESTED** [review]
I like the goal of this PR -- simplifies things a bit -- makes the output easier to read too -- can you clean it up a bit?

and do you have any sample runs using this branch?

**Comment by poulet42** [comment]
> I like the goal of this PR -- simplifies things a bit -- makes the output easier to read too -- can you clean it up a bit?

Appreciate it :) Do you have pointers of things I could clean? 

> and do you have any sample runs using this branch?

The CI job from my second commit already tests `no-lockfile`, `arguments` and no inputs, should I add another case?

**Comment by NullVoxPopuli** [comment]
> Do you have pointers of things I could clean?

it's just that you said to ignore certain changes? made me think they were temporary

> (please ignore changes on ci.yml, it's just to test regressions)

> The CI job from my second commit already tests no-lockfile, arguments and no inputs, should I add another case?

I suppose the only thing we'd need to assert is "no error", which GH does for us via red/green status?

**Comment by poulet42** [comment]
I removed the extra commit, adding a link [here](https://github.com/NullVoxPopuli/action-setup-pnpm/actions/runs/5176657987/jobs/9325744443) for the green runs against these changes :)

**Review by NullVoxPopuli — APPROVED** [review]
thank you!

**Pull request merged**
