### PR TITLE
Test the GitHub action

### PR DESCRIPTION
**Pull request by leosuncin**
Add workflow to test that the action works as expected

 - Work across different OS
 - Work with different version of Node.js
 - Install the dependencies with pnpm

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Thank you for doing this! this is great!!

**Comment by leosuncin** [comment]
Ups, look like the "Licensed" workflow uses npm

https://github.com/NullVoxPopuli/action-setup-pnpm/blob/204f670cee97eb251873d1346e052c633721e217/.github/workflows/license.yml#L15

And I switched to pnpm to test that the github action installs the dependencies

**Comment by leosuncin** [comment]
I [solved it](https://github.com/NullVoxPopuli/action-setup-pnpm/pull/4/commits/d6b9bd09cd2885595891a202c9769e19fc856b2a) by installing licensed in the workflow instead of using the [action](actions/reusable-workflows/.github/workflows/licensed.yml)

**Comment by NullVoxPopuli** [comment]
thank you!!! <3

**Pull request merged**
